version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: localhost
      POSTGRES_DB: profiler
    ports:
      - "5432:5432"

